#!/usr/bin/env bash
# Displays all currently running processes in a user-readable, hierarchical format including background and system processes

ps -eo user,pid,ppid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest
