#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely and handles SIGTERM signal

sigterm_handler() {
    echo "I am invincible!!!"
}

trap sigterm_handler SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
