#!/usr/bin/env bash
# This script displays numbers from 1 to 20 with superstitious "bad luck" messages for specific numbers

counter=1
while [ $counter -le 20 ]
do
    echo $counter
    case $counter in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    ((counter++))
done
